#!/usr/bin/python3


import sys
import random
import time


def checkPrime(argVal, k=20):
    '''
    '''
    if argVal == 2 or argVal == 3:
        return True
    if argVal < 2 or argVal % 2 == 0:
        return False


    d = argVal - 1
    rVal = 0
    while d % 2 == 0:
        d //= 2
        rVal += 1


    for _ in range(k):
        a = random.randint(2, argVal - 2)
        x = pow(a, d, argVal)
        if x == 1 or x == argVal - 1:
            continue
        for _ in range(rVal - 1):
            x = pow(x, 2, argVal)
            if x == argVal - 1:
                break
        else:
            return False


    return True


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        exit()


    input_file = sys.argv[1]


    try:
        with open(input_file, 'r') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print("File not found")
        exit()


    start_time = time.time()


    argVal = int(lines[0].strip())


    for i in range(2, argVal//2):
        if argVal % i == 0 and checkPrime(i) and checkPrime(argVal//i):
            print(f"{argVal}={i}*{argVal//i}")
            break


        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()

